// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://geeuxuskzdnpcuirrkqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdlZXV4dXNremRucGN1aXJya3F2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MzQ2ODAsImV4cCI6MjA2MjExMDY4MH0.YS4Kjb_cxMq7IjUG_UVU7GE0rQF0A09stuWbPhPhqDg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);